version:'3'
services:
  wordpress:
    container_name : "sample_wordpress"
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 8080:80

  wordpress_db:
    image : mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - wordpress_db:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASWORD: password